export enum section {
  heroVideo = "Hero Video",
  normalImage = "Normal Image",
  flipCardLayout = "Flip Card Layout",
  featuredSource = "Featured Source",
  testimonialCards = "Testimonial Cards",
  testimonial = "Testimonial Section",
  lineBreak = "Line Break",
  imageCard = "Image Card",
  heading = "Heading",
  image = "Image",
  buttons = "Buttons",
  textBlock = "Text Block",
  oneColumnLayout = "One Column Layout",
  twoColumnLayout = "Two Column Layout",
  imageCaraousel = "Carousel",
  newImageCaraousel="NewCarousel",
  imageSlider="Slider",
  heroImage = "Hero Image",
  fullImage ="Full Image",
  pointers = "Pointers",
  cards="Cards",
  productCard = "Product Cards",
  brandList = "Brand List",
  brandLogo = "Brand Logo",
  banner = "Banner",
  footer = "Footer",
  tabComponentLayout = "Tab Component Layout",
  verticalTabComponentLayout="Vertial Tab Component Layout",
  bulletPoints = "Bullet Points",
  teams = "Team Section",
  blogspreview = "Blogs Preview",
  allBlogsSection = "All Blogs",
  allResourceSection = "Resources",
  blogPost = "Blog Post",
  resourceItem = "Resource Items",
  formEmbbed = "Form Embbed",
}

export enum colors {
  White = "#FFFFFF",
  Secondary = "#0D0F1C",
  LightBlue = "#E7F3F8",
  Blue = "#B6DAEA",
  DarkBlue = "#D1E0FF",
  Green = "#B8F5E6",
  Black = "#171717",
  Transparent = "transparent",
  Alt = "#EAECF5",
  back="#000000"
}

export enum dialogType {
  withImage = "With Image",
  withoutImage = "Without Image",
}
